# Site settings
title: "My Simple Website"
description: "A minimalist website built with Jekyll and the no-style-please theme"
author: "Your Name"
email: "your.email@example.com"
url: "https://andrewcai31.github.io" # Replace with your actual URL
baseurl: "/webs" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Collections
collections:
  things:
    output: true
    permalink: /things/:name/
  writing:
    output: true
    permalink: /writing/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "things"
    values:
      layout: "thing"
  - scope:
      path: ""
      type: "writing"
    values:
      layout: "writing"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Kramdown settings for LaTeX support
kramdown:
  math_engine: katex
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false 