# Site settings
title: "andrew cai"
description: "my little website"
author: "andrew cai"
email: "andrewcai31@gmail.com"
url: "https://andrewc.ai"
baseurl: ""

# Remote theme (GitHub Pages compatible)
remote_theme: riggraz/no-style-please

# Theme configuration
theme_config:
  appearance: "auto"
  back_home_text: ".." 
  date_format: "%Y-%m-%d"
  show_description: true

# Build settings
markdown: kramdown
permalink: /:title/

# Collections
collections:
  writings:
    output: true
    permalink: /writings/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Kramdown settings for LaTeX support
kramdown:
  math_engine: katex
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed 