# Site settings
title: "My Simple Website"
description: "A minimalist website built with Jekyll and the no-style-please theme"
author: "Andrew Cai"
email: "your.email@example.com"
url: "https://andrewc.ai"
baseurl: ""

# Theme
theme: no-style-please

# Theme configuration
theme_config:
  appearance: "auto"
  back_home_text: ".." 
  date_format: "%Y-%m-%d"
  show_description: true

# Build settings
markdown: kramdown
permalink: /:title/

# Collections
collections:
  things:
    output: true
    permalink: /things/:name/
  writing:
    output: true
    permalink: /writing/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Kramdown settings for LaTeX support
kramdown:
  math_engine: katex
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed 